### PR TITLE
Stable support

### PR DESCRIPTION
**Pull request by dtolnay**
This PR makes typed-html work with stable rustc as of version 1.30.0. Feel free to close if you prefer to wait for proc_macro_hygiene, although I believe that is quite a ways away from being stabilized.

### CODE REVIEW

**Comment by bodil** [comment]
This is a tough one - I'm amazed that the error reporting is as good as this, because I couldn't figure out how to do this myself with the proc_macros2 stack - it's the reason I stuck with the native stuff. On the other hand, the errors aren't *quite* as good now, even though they're strictly adequate. Might be a price worth paying for stable support, let alone how much cleaner the code would be with the improved quote macro - I'll have to think about it for a little bit.

It's a very impressive PR in any case, thanks!

**Comment by dtolnay** [comment]
Which errors are you looking at that are not quite as good? I didn't get a chance to test all the error codepaths locally so it could be an omission (filed #2 to follow up on automated testing).

**Comment by bodil** [comment]
The errors generated by the HTML parsers come out as two errors rather than an error with an attached note, but tbh that's mostly just a cosmetic issue.

Anyway, I've thought about it and decided it's definitely worth merging. Thanks. 😊

**Comment by dtolnay** [comment]
I filed #5 to follow up on the cosmetic issue.

**Pull request merged**
