### PR TITLE
Use Vec to implement the Events iterators

### PR DESCRIPTION
**Pull request by cuviper**
Using `vec::IntoIter` is much simpler than a deeply nested `Chain`,
compiling faster and avoiding the deeper recursion limit reported in
[rust#71359](https://github.com/rust-lang/rust/issues/71359).

### CODE REVIEW

**Comment by cuviper** [comment]
cc @chrysn #115 

I'm not familiar with actually using this crate, as I just looked into this for the Rust issue. I'd be interested to know how this affects performance -- I _hope_ the added cost of `Vec` allocation is offset by the much greater simplicity of the iterators.

**Comment by chrysn** [comment]
In the test I've crudely sketched up, this behaves equivalently to the #115 version (which solves the same issue but just ups the recursion depth). A rough comparison indicates equal or slightly-better performance of this over #115, by I have zero trust in the test setup as I don't really know what I'm benchmarking or what for.

I really can't say anything about the suitability of the Vec allocation, as I don't yet use the parts of typed-html that deal with exotic allocators (like dodrio on bumpalo) where it may or may not be relevant.

**Comment by bodil** [comment]
The Vec shouldn't have an impact on Dodrio, it couldn't be allocated using a bump allocator in any case.

Anyway, good work, merging 👍

**Comment by cuviper** [comment]
@bodil could you publish a new release, so we might feel safer in closing that Rust issue? :slightly_smiling_face:

**Comment by andybalaam** [comment]
Because there is no release yet, I depended directly on the latest git commit in my Cargo.toml like this:

```typed-html = { git = "https://github.com/bodil/typed-html#4c13ecca" }```

and my broken compile is fixed!

To feed the search engines, the compile error I had before was:

```error: overflow representing the type `std::option::Option<&T>` ```

**Comment by dullbananas** [comment]
@bodil you should release this fix to crates.io

**Pull request merged**
